[package]
name = "image-decrypt"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/zy97/image-decrypt"

[dependencies]
actix-web = "4"
reqwest = "0.12"
deno_core = "0.354.0"
serde_v8 = "0.263.0"
base64 = "0.22.1"
moka = { version = "0.12.10", features = ["future"] }
